### PR TITLE
Add option `pageTitle` to configure HTML <title> of the report page

### LINKED ISSUE #70: No options for configuring mocha HTML <title> attribute
please add the feature for configuring the <title> attribute using reporter-options. It's always stays as Mocha Awesome Report Card

### PR DESCRIPTION
**Pull request by armno**
- Fixes #70 
- Related with #75 

🤘

### CODE REVIEW

**Comment by adamgruber** [comment]
@armno Nice work. Thanks for this. One change I would make is to rename `pageTitle` to `reportPageTitle`. This makes it more consistent with the other options and consistent with the option in v2.

**Comment by adamgruber** [comment]
@armno 👍

**Comment by armno** [comment]
hey @adamgruber you were too fast!

i found a few more changes to the code that should be updated. it's here https://github.com/armno/mochawesome/commit/507d9439ef4d07d06e44c5b9ed9a41ca546a5555

**Comment by adamgruber** [comment]
@armno doh! thanks for catching those too. can you open it as a new PR?

**Comment by armno** [comment]
@adamgruber sure! will do.

**Pull request merged**
