### PR TITLE
Displays report title also in <title> element in HTML head

### PR DESCRIPTION
**Pull request by sir-marc**
should fix report #70.
Adds the report title as the page title

### CODE REVIEW

**Comment by adamgruber** [comment]
Thanks for this but I think #70 is looking for a new option for the title and not just to put the `reportTitle` in there. I can see when you may want them to be different.

**Comment by sir-marc** [comment]
So should adding a reportSiteTitle to the config and using that in template be enough?

**Comment by adamgruber** [comment]
Yep. It should follow how the other options are configured. I think it should be called `pageTitle`.

**Comment by sir-marc** [comment]
Only those two changes?
I'm not able to test it, because the gulp script fails.

**Pull request closed without merging**
