### PR TITLE
Typescript definitions for addContext

### PR DESCRIPTION
**Pull request by Noderino**

### CODE REVIEW

**Comment by adamgruber** [comment]
This project doesn't currently use Typescript.

**Comment by Noderino** [comment]
I am using mochawesome in many Typescript projects including Angular 2+ projects. This definition provides type checking and intellisense in TS files. It will be good if you can distribute this definition with package.

**Comment by AerionDyseti** [comment]
Even though mochawesome itself isn't written in Typescript, this edit would make it much easier to utilize addContext for those who do. It would also provide intellisense for common editors like VS Code.

**Comment by adamgruber** [comment]
I realize there is a use for adding these type definitions. An alternate solution to adding these within the project itself is to open a PR on https://github.com/DefinitelyTyped/DefinitelyTyped. The definitions could then be published under the @types/mochawesome name.

One of my concerns is that I honestly don't know a whole lot about creating type definitions. Therefore I cannot speak to the accuracy of this implementation and don't feel comfortable including the file in this project without some kind of validation that it is correct. Further, once included, maintaining the type definitions becomes an added responsibility.

**Pull request closed without merging**
